package de.giftbox.domain_ejb;

// Generated 29.05.2013 11:21:39 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Benutzer generated by hbm2java
 */
@Entity
@Table(name = "benutzer", catalog = "android")
public class Benutzer implements java.io.Serializable {

	private static final long serialVersionUID = -8744665496994391214L;
	
	private Integer idBenutzer;
	private Geschenkliste geschenkliste;
	private String username;
	private String passwort;
	private String kommentar;
	private String email;
	private Set geschenklisten = new HashSet(0);
	private Set geschenklisteHasGeschenke = new HashSet(0);
	private Set bewertungen = new HashSet(0);

	public Benutzer() {
	}

	public Benutzer(String email) {
		this.email = email;
	}

	public Benutzer(Geschenkliste geschenkliste, String username,
			String passwort, String kommentar, String email,
			Set geschenklisten, Set geschenklisteHasGeschenke, Set bewertungen) {
		this.geschenkliste = geschenkliste;
		this.username = username;
		this.passwort = passwort;
		this.kommentar = kommentar;
		this.email = email;
		this.geschenklisten = geschenklisten;
		this.geschenklisteHasGeschenke = geschenklisteHasGeschenke;
		this.bewertungen = bewertungen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idBenutzer", unique = true, nullable = false)
	public Integer getIdBenutzer() {
		return this.idBenutzer;
	}

	public void setIdBenutzer(Integer idBenutzer) {
		this.idBenutzer = idBenutzer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Geschenkliste_idGeschenkliste")
	public Geschenkliste getGeschenkliste() {
		return this.geschenkliste;
	}

	public void setGeschenkliste(Geschenkliste geschenkliste) {
		this.geschenkliste = geschenkliste;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "passwort", length = 45)
	public String getPasswort() {
		return this.passwort;
	}

	public void setPasswort(String passwort) {
		this.passwort = passwort;
	}

	@Column(name = "kommentar", length = 45)
	public String getKommentar() {
		return this.kommentar;
	}

	public void setKommentar(String kommentar) {
		this.kommentar = kommentar;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "benutzer_has_geschenkliste", catalog = "android", joinColumns = { @JoinColumn(name = "idBenutzer", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_Geschenkliste", nullable = false, updatable = false) })
	public Set getGeschenklisten() {
		return this.geschenklisten;
	}

	public void setGeschenklisten(Set geschenklisten) {
		this.geschenklisten = geschenklisten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benutzer")
	public Set getGeschenklisteHasGeschenke() {
		return this.geschenklisteHasGeschenke;
	}

	public void setGeschenklisteHasGeschenke(Set geschenklisteHasGeschenke) {
		this.geschenklisteHasGeschenke = geschenklisteHasGeschenke;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benutzer")
	public Set getBewertungen() {
		return this.bewertungen;
	}

	public void setBewertungen(Set bewertungen) {
		this.bewertungen = bewertungen;
	}

}
