package de.giftbox.domain_ejb;

// Generated 29.05.2013 13:40:32 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Geschenk generated by hbm2java
 */
@Entity
@Table(name = "geschenk", catalog = "giftbox")
public class Geschenk implements java.io.Serializable {

	private Integer idGeschenk;
	private String bezeichnung;
	private String kategorie;
	private Double preis;
	private String ort;
	private String link;
	private String kommentar;
	private Set geschenklisteHasGeschenks = new HashSet(0);
	private Set bewertungens = new HashSet(0);

	public Geschenk() {
	}

	public Geschenk(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	public Geschenk(String bezeichnung, String kategorie, Double preis,
			String ort, String link, String kommentar,
			Set geschenklisteHasGeschenks, Set bewertungens) {
		this.bezeichnung = bezeichnung;
		this.kategorie = kategorie;
		this.preis = preis;
		this.ort = ort;
		this.link = link;
		this.kommentar = kommentar;
		this.geschenklisteHasGeschenks = geschenklisteHasGeschenks;
		this.bewertungens = bewertungens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idGeschenk", unique = true, nullable = false)
	public Integer getIdGeschenk() {
		return this.idGeschenk;
	}

	public void setIdGeschenk(Integer idGeschenk) {
		this.idGeschenk = idGeschenk;
	}

	@Column(name = "bezeichnung", nullable = false, length = 45)
	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	@Column(name = "kategorie", length = 45)
	public String getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(String kategorie) {
		this.kategorie = kategorie;
	}

	@Column(name = "preis", precision = 22, scale = 0)
	public Double getPreis() {
		return this.preis;
	}

	public void setPreis(Double preis) {
		this.preis = preis;
	}

	@Column(name = "ort", length = 45)
	public String getOrt() {
		return this.ort;
	}

	public void setOrt(String ort) {
		this.ort = ort;
	}

	@Column(name = "link", length = 256)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "kommentar", length = 140)
	public String getKommentar() {
		return this.kommentar;
	}

	public void setKommentar(String kommentar) {
		this.kommentar = kommentar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "geschenk")
	public Set getGeschenklisteHasGeschenks() {
		return this.geschenklisteHasGeschenks;
	}

	public void setGeschenklisteHasGeschenks(Set geschenklisteHasGeschenks) {
		this.geschenklisteHasGeschenks = geschenklisteHasGeschenks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "geschenk")
	public Set getBewertungens() {
		return this.bewertungens;
	}

	public void setBewertungens(Set bewertungens) {
		this.bewertungens = bewertungens;
	}

}
