package de.giftbox.domain_ejb;

// Generated 29.05.2013 11:21:39 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Geschenkliste generated by hbm2java
 */
@Entity
@Table(name = "geschenkliste", catalog = "android")
public class Geschenkliste implements java.io.Serializable {

	private static final long serialVersionUID = -7356832419380756457L;
	
	private int idGeschenkliste;
	private String name;
	private Set geschenklisteHasGeschenke = new HashSet(0);
	private Geschenk geschenk;
	private Set benutzers = new HashSet(0);
	private Set benutzers_1 = new HashSet(0);

	public Geschenkliste() {
	}

	public Geschenkliste(int idGeschenkliste, String name) {
		this.idGeschenkliste = idGeschenkliste;
		this.name = name;
	}

	public Geschenkliste(int idGeschenkliste, String name,
			Set geschenklisteHasGeschenke, Geschenk geschenk, Set benutzers,
			Set benutzers_1) {
		this.idGeschenkliste = idGeschenkliste;
		this.name = name;
		this.geschenklisteHasGeschenke = geschenklisteHasGeschenke;
		this.geschenk = geschenk;
		this.benutzers = benutzers;
		this.benutzers_1 = benutzers_1;
	}

	@Id
	@Column(name = "idGeschenkliste", unique = true, nullable = false)
	public int getIdGeschenkliste() {
		return this.idGeschenkliste;
	}

	public void setIdGeschenkliste(int idGeschenkliste) {
		this.idGeschenkliste = idGeschenkliste;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "geschenkliste")
	public Set getGeschenklisteHasGeschenke() {
		return this.geschenklisteHasGeschenke;
	}

	public void setGeschenklisteHasGeschenke(Set geschenklisteHasGeschenke) {
		this.geschenklisteHasGeschenke = geschenklisteHasGeschenke;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "geschenkliste")
	public Geschenk getGeschenk() {
		return this.geschenk;
	}

	public void setGeschenk(Geschenk geschenk) {
		this.geschenk = geschenk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "geschenkliste")
	public Set getBenutzers() {
		return this.benutzers;
	}

	public void setBenutzers(Set benutzers) {
		this.benutzers = benutzers;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "geschenklistes")
	public Set getBenutzers_1() {
		return this.benutzers_1;
	}

	public void setBenutzers_1(Set benutzers_1) {
		this.benutzers_1 = benutzers_1;
	}

}
