package de.giftbox.domain;

// Generated 29.05.2013 13:40:32 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Benutzer generated by hbm2java
 */
@Entity
@Table(name = "benutzer", catalog = "giftbox")
public class Benutzer implements java.io.Serializable {

	private static final long serialVersionUID = -2051207650344258994L;

	private Integer idBenutzer;
	private String username;
	private String passwort;
	private String kommentar;
	private String email;
	private Set<Geschenkliste> geschenklisten = new HashSet<Geschenkliste>(0);
	private Set<GeschenklisteHasGeschenk> geschenklisteHasGeschenk = new HashSet<GeschenklisteHasGeschenk>(
			0);
	private Set<Bewertungen> bewertungen = new HashSet<Bewertungen>(0);

	public Benutzer() {
	}

	public Benutzer(String email) {
		this.email = email;
	}

	public Benutzer(String username, String passwort, String kommentar,
			String email, Set<Geschenkliste> geschenklisten,
			Set<GeschenklisteHasGeschenk> geschenklisteHasGeschenk,
			Set<Bewertungen> bewertungen) {
		this.username = username;
		this.passwort = passwort;
		this.kommentar = kommentar;
		this.email = email;
		this.geschenklisten = geschenklisten;
		this.geschenklisteHasGeschenk = geschenklisteHasGeschenk;
		this.bewertungen = bewertungen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_Benutzer", unique = true, nullable = false)
	public Integer getIdBenutzer() {
		return this.idBenutzer;
	}

	public void setIdBenutzer(Integer idBenutzer) {
		this.idBenutzer = idBenutzer;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "passwort", length = 45)
	public String getPasswort() {
		return this.passwort;
	}

	public void setPasswort(String passwort) {
		this.passwort = passwort;
	}

	@Column(name = "kommentar", length = 45)
	public String getKommentar() {
		return this.kommentar;
	}

	public void setKommentar(String kommentar) {
		this.kommentar = kommentar;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "benutzer_has_geschenkliste", catalog = "giftbox", joinColumns = { @JoinColumn(name = "id_Benutzer", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_Geschenkliste", nullable = false, updatable = false) })
	public Set<Geschenkliste> getGeschenklisten() {
		return this.geschenklisten;
	}

	public void setGeschenklisten(Set<Geschenkliste> geschenklisten) {
		this.geschenklisten = geschenklisten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benutzer")
	public Set<GeschenklisteHasGeschenk> getGeschenklisteHasGeschenk() {
		return this.geschenklisteHasGeschenk;
	}

	public void setGeschenklisteHasGeschenk(
			Set<GeschenklisteHasGeschenk> geschenklisteHasGeschenk) {
		this.geschenklisteHasGeschenk = geschenklisteHasGeschenk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benutzer")
	public Set<Bewertungen> getBewertungen() {
		return this.bewertungen;
	}

	public void setBewertungen(Set<Bewertungen> bewertungen) {
		this.bewertungen = bewertungen;
	}

}
