package de.giftbox.domain;

// Generated 29.05.2013 11:21:39 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;


/**
 * Geschenk generated by hbm2java
 */
@Entity
@Table(name = "geschenk", catalog = "android")
public class Geschenk implements java.io.Serializable {

	private static final long serialVersionUID = -2722029944688724337L;
	
	private Integer idGeschenk;
	private Geschenkliste geschenkliste;
	private String bezeichnung;
	private String kategorie;
	private Double preis;
	private String ort;
	private String link;
	private String kommentar;
	private Set geschenklisteHasGeschenke = new HashSet(0);
	private Set bewertungen = new HashSet(0);

	public Geschenk() {
	}

	public Geschenk(Geschenkliste geschenkliste, String bezeichnung) {
		this.geschenkliste = geschenkliste;
		this.bezeichnung = bezeichnung;
	}

	public Geschenk(Geschenkliste geschenkliste, String bezeichnung,
			String kategorie, Double preis, String ort, String link,
			String kommentar, Set geschenklisteHasGeschenke, Set bewertungen) {
		this.geschenkliste = geschenkliste;
		this.bezeichnung = bezeichnung;
		this.kategorie = kategorie;
		this.preis = preis;
		this.ort = ort;
		this.link = link;
		this.kommentar = kommentar;
		this.geschenklisteHasGeschenke = geschenklisteHasGeschenke;
		this.bewertungen = bewertungen;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "geschenkliste"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idGeschenk", unique = true, nullable = false)
	public Integer getIdGeschenk() {
		return this.idGeschenk;
	}

	public void setIdGeschenk(Integer idGeschenk) {
		this.idGeschenk = idGeschenk;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Geschenkliste getGeschenkliste() {
		return this.geschenkliste;
	}

	public void setGeschenkliste(Geschenkliste geschenkliste) {
		this.geschenkliste = geschenkliste;
	}

	@Column(name = "bezeichnung", nullable = false, length = 45)
	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	@Column(name = "kategorie", length = 45)
	public String getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(String kategorie) {
		this.kategorie = kategorie;
	}

	@Column(name = "preis", precision = 22, scale = 0)
	public Double getPreis() {
		return this.preis;
	}

	public void setPreis(Double preis) {
		this.preis = preis;
	}

	@Column(name = "ort", length = 45)
	public String getOrt() {
		return this.ort;
	}

	public void setOrt(String ort) {
		this.ort = ort;
	}

	@Column(name = "link", length = 256)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "kommentar", length = 140)
	public String getKommentar() {
		return this.kommentar;
	}

	public void setKommentar(String kommentar) {
		this.kommentar = kommentar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "geschenk")
	public Set getGeschenklisteHasGeschenke() {
		return this.geschenklisteHasGeschenke;
	}

	public void setGeschenklisteHasGeschenke(Set geschenklisteHasGeschenke) {
		this.geschenklisteHasGeschenke = geschenklisteHasGeschenke;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "geschenk")
	public Set getBewertungen() {
		return this.bewertungen;
	}

	public void setBewertungen(Set bewertungen) {
		this.bewertungen = bewertungen;
	}

}
